dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
  - OpenZeppelin/openzeppelin-contracts@4.2.0
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.2.0'


networks:
  default: development
  mainnet-fork:
    usdc_usd_price_feed: '0x8fffffd4afb6115b954bd326cbe7b4ba576818f6'
    usdt_usd_price_feed: '0x3e7d1eab13ad0104d2750b8863b489d65364e32d'
    verify: False


project_id: ${WEB3_ALCHEMY_PROJECT_ID}